[Settings]
Tag = "{red}[CSS] "
DeadName = "☠"
NoneName = "{White}(NONE)"
SpecName = "{Purple}(SPEC)"
TName = "{Yellow}(T)"
CTName = "{Blue}(CT)"

[Database]
Enabled = false
Host = "localhost"
Port = 3306
User = "root"
Password = ""
DatabaseName = "cs2_tags"
TableName = "player_colors"

[Commands]
TagsReload = [ "css_tags_reload" ]
Visibility = [ "css_toggletags", "css_visibility" ]
NameColor = [ "css_namecolor" ]
ChatColor = [ "css_chatcolor" ]

[Default]
ScoreTag = ""
ChatTag = "{Grey}[Player]"
ChatColor = "{White}"
NameColor = "{TeamColor}"
ChatSound = true

[[Tags]]
Role = "76561199165718810"
ScoreTag = ""
ChatTag = "{Red}[schwarper] "
ChatColor = "{green}"
NameColor = "{TeamColor}"
ChatSound = false

[[Tags]]
Role = "#OWNER"
ScoreTag = ""
ChatTag = "{Red}[OWNER] "
ChatColor = "{green}"
NameColor = "{TeamColor}"